---

- name: Install PostgreSQL
  apt: name={{item}} update_cache=yes state=installed
  with_items:
    - postgresql-9.3
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: db={postgresql_db}} state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{postgresql_db}}
                   name={{postgresql_username}}
                   password={{postgresql_user_passwd}}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{postgresql_user}}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present

- name: Allow md5 authentication for local connections
  lineinfile: >
    dest='/etc/postgresql/9.3/main/pg_hba.conf'
    regexp='^local.+all.+all.+peer$' backrefs=yes
    line='local all all md5'
  tags: packages

- name: Restart Postgresql
  service: name=postgresql state=restarted enabled=yes

- name: Install Postgres client components
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - libpq-dev
    - python-psycopg2
  tags: packages
